services:
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile.dev
    ports:
      - "${FRONTEND_DEV_PORT:-5173}:5173"
    environment:
      BACKEND_URL: http://backend:3000
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/index.html:/app/index.html
      - ./frontend/public:/app/public
    develop:
      watch:
        - action: rebuild
          path: ./frontend/package.json
        - action: rebuild
          path: ./schema/openapi.json
